---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность регистрироваться и входить в личный кабинет магазина
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность удалять товары из корзины по единицам или всю позицию сразу
  - Пользователь должен иметь возможность указывать количество товара при добавлении в корзину
  - Пользователь должен иметь возможность отменить заказ, если он был ошибочно сформирован
  - Пользователь должен оставлять номер телефона или e-mail для связи по заказу
  - Пользователь должен иметь возможность просматривать уже оформленные заказы
